### PR TITLE
fix port

### LINKED ISSUE #44: Impossible to reach webserver once built
Thanks to the previous #42, the webserver builds successfully on Rpi.
However, it seems not possible to reach it (either localy or from another machine on the network)

I receive the following error ``curl: (56) Recv failure: Connection reset by peer  `when doing a curl http://localhost:8002/docs`to reach the documentaion. 

Having no time to investigate further, I am opening this issue, hoping that this just an oversight from my side and it will quickly closed :) 

Thanks a lot

### PR DESCRIPTION
**Pull request by MateoLostanlen**
This small PR will close #44

The api port and expose port should be the same inside the docker

### CODE REVIEW

**Comment by fe51** [comment]
Hello there, thaks for the PR, 

Just to be sur, thanks to this update, do you successfully reach the webserver (llike the doc), whether from a machine or locally ?

**Review by fe51 — COMMENTED** [review]
Hello @MateoLostanlen , thanks for the PR,

Just to be sure, thanks to this update, do you successfully reach the webserver (like the doc), whether from a machine or locally ?

**Comment by MateoLostanlen** [comment]
Only tested it on my pc but it works

**Review by fe51 — APPROVED** [review]
Let's go then !

**Pull request merged**
