### PR TITLE
Add precommit hook

### PR DESCRIPTION
**Pull request by RonanMorgan**
Install precommit hook, the same configuration as in pyro-engine.

### CODE REVIEW

**Review by MateoLostanlen — CHANGES_REQUESTED** [review]
Hi @RonanMorgan, thnaks for your PR ! please can you add the setup-docker-compose.sh script to the script folder and generate a docker-compose.override.yml ignore by git that will be read automatically in order to avoid changing a file track by git

**Review by MateoLostanlen — CHANGES_REQUESTED** [review]
Hello, thanks for the update. 

Please do not change stuff that have nothing to do with this PR you should not format engine.py here

**Comment by RonanMorgan** [comment]
@MateoLostanlen sorry I thought that it would be very small and there is already so much PR open so that I prefered move forward

**Comment by MateoLostanlen** [comment]
@RonanMorgan what do you mean you're not going to continue with this PR?

**Comment by RonanMorgan** [comment]
TODO : if we use the precommit hook, we should remove the linting part in the makefile and also clean up the workflows...

**Pull request closed without merging**
