### PR TITLE
refactor: Updated src/capture.py

### PR DESCRIPTION
**Pull request by frgfm**
This PR introduces the following modifications:
- refactors class definitions from src/run.py to src/controller.py
- updated src/capture.py to use those classes
- added JPEG 50 quality before saving/uploading pictures

Any feedback is welcome!

### CODE REVIEW

**Comment by fe51** [comment]
First of all thanks for the PR !

Then some naive questions :)
why system controler.py is in src and not in pyroengine ?
why the arg is name "cache "to specify where to save snapshots ?

**Review by MateoLostanlen — CHANGES_REQUESTED** [review]
Thank you for this refacto, it is much better like that. However, it doesn't work as it is, there is an import problem. I haven't looked into it in detail. Have you tried on the pi / in the docker?
I think it would be better to have the controller in the pyroengine package. What do you think ?

Also, can you update the docker accordingly? Especially with:

`COPY ./src/capture.py /usr/src/app/capture.py`

**Comment by frgfm** [comment]
The last commits solve the import issue :+1:

**Review by MateoLostanlen — APPROVED** [review]
Sorry for this late review, all good for me ! Thanks

**Review by fe51 — APPROVED** [review]

**Pull request merged**
