### PR TITLE
Add bash script for internet failures scenario

### PR DESCRIPTION
**Pull request by chloeskt**
Hi everyone, 

In this PR you can find a proposition for internet failures scenario. This script bash will then be added on the main rpi (using pyro-sys-setup) and will be put in a cron job so that in it run every 15 minutes for instance (the number here is chosen arbitrarily, if you have better ideas, feel free to tell me).

The flow is the following:
```
Ping internet: 
	- if success: 
		Ping vpn:
		- if success: ok exit 
		- if failure: restart vpn

	- if failure: restart of network interfaces (all interfaces because I don't know which internet the 4G modem will take)
sleep 60 sec
Ping internet again (to make sure that we have internet):
	- if success: ok exit
	- if failure: reboot
```

What do you think ?

### CODE REVIEW

**Comment by blenzi** [comment]
Thanks @chloeskt, looks good to me! I guess there is no easy way to add a test? One suggestion is to call it `check_internet_connection` and add the description above to the file.

**Comment by MateoLostanlen** [comment]
Hi @chloeskt , thanks for the PR, Just one question. If there is a problem, your script will reboot the pizero. What happens after that? How do you restart the runner? Shouldn't this reboot be managed by the pi central to restart the pizero afterwards ?

**Comment by chloeskt** [comment]
> Hi @chloeskt , thanks for the PR, Just one question. If there is a problem, your script will reboot the pizero. What happens after that? How do you restart the runner? Shouldn't this reboot be managed by the pi central to restart the pizero afterwards ?

Hello Mateo ! This script bash will only be run on the main rpis since they are the ones with the vpn and the internet connexion not the rpi with camera. If the main rpi reboots, the monitor script will be launch again as it is in a cron job starting on reboot. The rpi with camera are not affected by this bash script.

**Comment by chloeskt** [comment]
> Thanks @chloeskt, looks good to me! I guess there is no easy way to add a test? One suggestion is to call it `check_internet_connection` and add the description above to the file.

Indeed no way to test on github. I've tested it a couple of times on my rpi of course, seemed to work fine. Also I integrated your suggestions, thanks !

**Comment by MateoLostanlen** [comment]
> 
> 
> > Hi @chloeskt , thanks for the PR, Just one question. If there is a problem, your script will reboot the pizero. What happens after that? How do you restart the runner? Shouldn't this reboot be managed by the pi central to restart the pizero afterwards ?
> 
> Hello Mateo ! This script bash will only be run on the main rpis since they are the ones with the vpn and the internet connection not the rpi with camera. If the main rpi reboots, the monitor script will be launch again as it is in a cron job starting on reboot. The rpi with camera are not affected by this bash script.

ok sorry I misunderstood. It's perfect then.

**Review by MateoLostanlen — APPROVED** [review]
All good, thanks !

**Pull request merged**
